//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNightr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUsers
    {
        public int EventUserId { get; set; }
        public int EventId { get; set; }
        public int UserId { get; set; }
        public int EventUserStatusId { get; set; }
        public System.DateTime LastActionOn { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual EventUserStatus EventUserStatus { get; set; }
        public virtual Users Users { get; set; }
    }
}
