//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNightr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.EventMovies = new HashSet<EventMovies>();
            this.EventUsers = new HashSet<EventUsers>();
        }
    
        public int EventId { get; set; }
        public int EventLeaderUserId { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> FilterSetId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventMovies> EventMovies { get; set; }
        public virtual Users Users { get; set; }
        public virtual FilterSets FilterSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventUsers> EventUsers { get; set; }
    }
}
